name: Build Push Branch Docker Image

on:
  push:
    branches:
      - '*'  # Trigger on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag from branch name
        id: extract_tag
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          TAG=${BRANCH_NAME%%-*}
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/sever3d/blockchain:${{ env.TAG }}
            docker.io/sever3d/blockchain:latest-branch
          platforms: linux/amd64,linux/arm64
          build-args: |
            ARG1=value1
            ARG2=value2
